version: "3.9"
services:
  mysql:
    image: mysql/mysql-server:8.0.27
    ports:
    - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: 'pass'
       MYSQL_DATABASE: 'db'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: 'pass'